// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _3CXCallogScrapper;

#nullable disable

namespace _3CXCallogScrapper.Migrations
{
    [DbContext(typeof(CallLogDbContext))]
    [Migration("20250419132106_AddStartTimeIndex")]
    partial class AddStartTimeIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_3CXCallogScrapper.Models.CallLogEntry", b =>
                {
                    b.Property<int>("SegmentId")
                        .HasColumnType("integer");

                    b.Property<string>("ActionDnCallerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActionDnDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ActionDnDn")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("ActionDnType")
                        .HasColumnType("integer");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<bool>("Answered")
                        .HasColumnType("boolean");

                    b.Property<double?>("CallCost")
                        .HasColumnType("double precision");

                    b.Property<int>("CallId")
                        .HasColumnType("integer");

                    b.Property<string>("DestinationCallerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DestinationDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DestinationDn")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("DestinationType")
                        .HasColumnType("integer");

                    b.Property<int>("Indent")
                        .HasColumnType("integer");

                    b.Property<bool>("QualityReport")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RingingDuration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceCallerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceDn")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int?>("SrcRecId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubrowDescNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TalkingDuration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SegmentId");

                    b.HasIndex("StartTime");

                    b.ToTable("CallLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
